### ISSUE TITLE
Unable to import classes from jar file.

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [vandeseer/easytable#132]
I want to use this repo in my project to generate PDF tables and for that I needed jar file which isn't provided in this repo. I got the jar file from here - https://mvnrepository.com/artifact/com.github.vandeseer/easytable and then imported into my Jdeveloper project but no luck when using it in my Jdeveloper IDE.

Any ideas?

**Comment by vandeseer** [comment]
Hey @Jay-ArBrouillard, 

since adding a jar file to a Java project is unrelated to this library I will close this issue. 

Still: It's actually pretty simple to include the jar file. You should use a build tool like gradle or maven and the library as a dependency there. Maybe have a look here: https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

You can include easytable like so: 

    <dependency>
        <groupId>com.github.vandeseer</groupId>
        <artifactId>easytable</artifactId>
        <version>0.8.4</version>
    </dependency>

Best,
Stefan
