### ISSUE TITLE
Building a Row does not set the Settings for the Cells leading to a NullPointerException

### ISSUE THREAD

**Issue by AdrianMiska** [vandeseer/easytable#23]
Hello :)

I think I found a bug with the new Settings object. I have taken this example from your tests and slightly modified it:

```
Row row = Row.builder()
                .add(CellText.builder().text(RandomStringUtils.randomAlphabetic(23)).span(2).borderWidth(1).build())
                .add(CellText.builder().text("Booz").build())
                .font(COURIER_BOLD).fontSize(8)
                .build();

tableBuilder.addRow(row);
```

If I call `row.getHeight()` now,  I get a NullPointerException. This used to work in version 0.1.0.  
If I first call `tableBuilder.build()` and `row.getHeight()` afterwards, it works just fine.  

I've identified that this is caused by the Cell Settings being filled with `fillingMergeBy` when the Table is built. But when the Row is built the Cells Settings remain empty.

Edit: I just noticed that it's not as easy as filling the Cells when the Rows are built. We still can't get the correct height because at that time we don't know yet if the Table will have line breaking :/

**Comment by vandeseer** [comment]
Hey @AdrianMiska, thanks a lot for reporting this and also thanks for already analysing! :) 
I will have a look as soon as I find time for it, which will most probably be next week ...

**Comment by vandeseer** [comment]
This is a tricky one. The basic issue is that there are inter-dependencies between the table and row settings as well as the column widths: In order to know the height of a cell we would need to know the column it is located in, but that only the table knows. But at the time we are building the row we don't know the table yet. 

I think that I initially planned not to expose the `getHeight()` methods from the `Row` and `Cell` classes (ie let them be package visible only) but I refactored the code at one point so that the structure itself is in a package of its own, not together with the `TableDrawer`. But since it is needed from there, I had to make it `public`. The idea of having builders for the rows and cells is merely to collect their properties (background color etc.) in a simple way, but not really to pre-calculate their height ;) 

So I would rather opt for either throwing an exception in case the cell is not yet rendered (ie the `build()` method of the `TableBuilder` has not yet been called) and only return a value if that is the case already. 

But what exactly is your use case? Maybe we can find a way to cover it in a different way? 
And still: of course getting a `NullPointerException` is not acceptable, we will need to fix that. ;)

**Comment by AdrianMiska** [comment]
Tricky indeed.

The implementation of my pull request allows a workaround by building an empty dummy table with the same columns and manually setting a dummy column for each cell when building it. Pretty hacky and I agree that a cleaner solution would be preferable.

My use case is rendering long tables over multiple pages. I'm looping over my data creating rows and for each row determine its height because the data is variable and so the height depends on margins, line breaks, etc. When the start point + the height of all rows reaches the footer of the page, I draw the table, create a new page and start a new table with the remaining data (or do the same thing again).

**Comment by vandeseer** [comment]
I added one commit to your pull request: that's how I would deal with it for now, because from my point of view the builders for the cells and rows are just some means of collecting their properties.

Regarding your use case: Could the "endY/multipage feature" be of use for you? I mean: 

    final PDDocument document = new PDDocument();

    TableDrawer drawer = TableDrawer.builder()
            .table(tableBuilder.build())
            .startX(50)
            .startY(100F)
            .endY(50F) // note: if not set, table is drawn over the end of the page
            .build();

    do {
        PDPage page = new PDPage(PDRectangle.A4);
        document.addPage(page);
        try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
            drawer.contentStream(contentStream).draw();
        }

        drawer.startY(page.getMediaBox().getHeight() - 50);
    } while (!drawer.isFinished());

    document.save("target/twoPageTable.pdf");
    document.close();

Also see [this file](https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/integrationtest/TwoPagesTableTest.java). Just run it and see how the output looks like. Maybe that would help already?

PS: Looks like I pushed some of my branches to your forked repo accidentally by not specifying the branch name, sorry for that.

**Comment by AdrianMiska** [comment]
Yeah, your changes make sense ^^

Wow, I didn't know about `endY`/`isFinished`. 
Looks a lot cleaner than what I'm currently doing. I'll try it.

**Comment by vandeseer** [comment]
Ok, I will merge the pull request then and close this issue. I hope you get your stuff done with the `endY` thingy ;) If this is useful for you or if you think there is something missing, let me know. Also I am always looking for nice examples, so if you think your table/document is worth sharing, also let me know and I will add it to the examples.
