### ISSUE TITLE
Sending the PDF via slack and I got wrong encoding

### ISSUE THREAD

**Issue by ZhiLiGod** [vandeseer/easytable#37]
All characters in the table show wired characters if I send the Pdf via Slack. Also, if I copy the text in the table from pdf to notepad, shows wired characters.

**Comment by vandeseer** [comment]
Does this also happen for a PDF document generated with PDFbox and the same fonr but without any tables?
What was the code and the resulting PDF? Could you post it here?

**Comment by ZhiLiGod** [comment]
I haven't tried to put plain text in PDF document but my program is using your table builder to build a table in PDF document. Below is how it looks like if I send the pdf via Slack.
![image](https://user-images.githubusercontent.com/29784334/55181558-c9d11800-5183-11e9-9dd8-13a5a45fa504.png).
It looks fine in Adobe but If I copy the text the notepad, shows wrong characters, seems like encoding problem
![image](https://user-images.githubusercontent.com/29784334/55181704-161c5800-5184-11e9-8442-f1c514c610b1.png)

**Comment by vandeseer** [comment]
I couldn't reproduce this behaviour and I from my point of view this shouldn't be related to easytable at all since it's just using what PDFBox provides it with. Most probably you will get the same issue not using easytable, i.e. having a PDF document with the same font but no tables. Hence I will close ticket.
