### ISSUE TITLE
Long cell text not handled in draw method of TableDrawer

### ISSUE THREAD

**Issue by reenanagdev** [vandeseer/easytable#55]
Long cell text spanning into multiple pages is not handled. Code gets stuck into infinite loop.

**Comment by vandeseer** [comment]
Do you have a minimum working example where this happens @reenanagdev?
And could you try to run your code with the latest `develop` branch? 

I think this is related to https://github.com/vandeseer/easytable/issues/28
A fix is already in the `develop` branch, but this is not yet released.

**Comment by reenanagdev** [comment]
Yes, Issue I am facing is same as #28. Can you please share the fix for same?

**Comment by reenanagdev** [comment]
I took the latest code from develop branch. However, I see that you are throwing an exception when row is too high to be displayed on single page. But it still does not display the required long text in pdf and generate it.

**Comment by reenanagdev** [comment]
My requirement is allow 4000 characters in single cell. Only ~1400 characters are getting displayed as of now which is maximum what can be accommodated on single page in the cell.

**Comment by vandeseer** [comment]
> I took the latest code from develop branch. However, I see that you are throwing an exception when row is too high to be displayed on single page. But it still does not display the required long text in pdf and generate it.

Well, yes: The "fix" is just to avoid the infinite loop. There is no mechanism to automatically split the text so that it fits in the page and the table continues on the next one. As of now I am also not planning to implement it, because I think that's very hard, especially given row and cell spanning. Users will need to split the texts themselves before drawing the table. 

If you have ideas how to implement this I am very open to see the concept. 
The same holds for pull requests, of course ... 😉
