### ISSUE TITLE
Hyperlink text

### ISSUE THREAD

**Issue by tcerdaITBA** [vandeseer/easytable#57]
Hello, first of all thank you very much for releasing this great library. I wanted to ask if there has been any update on Hyperlink support. I can see in issue #39 that this was mentioned. 

Moreover, I am in need also of underlining text so that it looks like a link. Is this currently possible?

Thank you very much.

**Comment by vandeseer** [comment]
Hi @tcerdaITBA,
as of now there hasn't been any update on hyperlinks and I didn't yet need this by myself.
However I find it pretty interesting ;) Since there is the possibility to add custom drawing functionality or even custom cells I am pretty optimistic that it can be done; given it's easy for a "regular" PDFBox document ...
I will have a look as soon as I find time (currently I am travelling).
Best,
Stefan

**Comment by hooperbill** [comment]
Attached is an archive of what I am using. PDF hyperlinks  require a bounding box around the text or image you want to hyperlink. In my implementation I just created a bounding box slightly smaller than the cell. You then bind an annotation and URI to the bounding box. This creates a hyperlink that is active for the entire cell. An issue I encountered is that the annotations are add to the page and while building or drawing I did not have access to the page. So resolve this I maintained a list of annotations outside of the easytable library and after drawing the table on a page I added my list of annotations. This solution works for me although I would prefer this functionality inside the easytable library.
[LinkCell.tar.gz](https://github.com/vandeseer/easytable/files/3791276/LinkCell.tar.gz)

**Comment by tcerdaITBA** [comment]
Thank you very much for your quick responses! I will also look into a possible implementation should I find time.
Best regards,
Tomás

**Comment by vandeseer** [comment]
Maybe it would make sense to extend the `TableDrawer` as well as the `DrawingContext` (which currently only holds the `PDPageContentStream`) to also hold the `PDPage`. This way one could have full access to the page and register the annotations there while drawing – which would mean that this data wouldn't have to be stored "outside". I think I will try to go in this direction ...

**Comment by vandeseer** [comment]
I have some stuff working now, but it's really not yet ready for releasing. After tinkering a bit more I will upload what I have onto a new branch. Will keep you posted.

**Comment by vandeseer** [comment]
The current state can be found in this branch: [feature/linked_text_cell](https://github.com/vandeseer/easytable/tree/feature/linked_text_cell)

See this file for how to use it: [LinkedTextCellTest.java](https://github.com/vandeseer/easytable/blob/feature/linked_text_cell/src/test/java/org/vandeseer/integrationtest/LinkedTextCellTest.java)

Note that it does currently not work for justified text and neither for links that are broken down due to not fitting the cell width. Besides that one can add arbitrarily many links to a text and it renders a line below and adds the annotation link to the page. 

I also plan to add a bit of styling possibilities (link text color and alike). But still work in progress ;)

**Comment by hooperbill** [comment]
Looking good! Glad we could help out.

**Comment by ligasgr** [comment]
Hi,
First of all... Thanks for great work!
On another note...
What is the release plan for this work? Any timelines in mind?
We are restricted to only using officially released versions so cannot use version sitting on a branch. Would be great to know what to expect.
Thanks!

**Comment by vandeseer** [comment]
Hi @ligasgr, 

actually I was not satisfied with the `LinkedTextCell` that is currently on the mentioned feature branch. The reason being that with the current approach one can neither do link coloring nor will it work properly with text brakes. 

Luckily someone else already created a nice library that is capable of adding [hyperlinks](https://github.com/ralfstuckert/pdfbox-layout/wiki/Hyperlinks) as part of a whole [layout library](https://github.com/ralfstuckert/pdfbox-layout/). So I am currently building a new type of cell that wraps this library. And I am pretty happy with what can be achieved this way. 

So back to your question: I plan to release this new feature within the next weeks, latest until the end of the year, probably even before christmas (depending on my free time). 

Best,
Stefan

PS: Just out of my personal curiosity: What are you using the library for? I mean what kind of tables?

**Comment by ligasgr** [comment]
That sounds brilliant! Thanks for your effort!
In our case we collate a lot of information from multiple systems to generate release runbooks and the links functionality is needed to point back to the locations in the original sources of information.
Hope this makes sense!

**Comment by vandeseer** [comment]
Just released version 0.6.0 where I introduced the new `ParagraphCell` type. Please find a bit more information in the README and in the linked new code examples. Let me know if it works for you (my tests were successful so far, otherwise I wouldn't have released :wink:)!
