### ISSUE TITLE
Support of Image in ParagraphCell

### ISSUE THREAD

**Issue by vikramtambe** [vandeseer/easytable#73]
As of now ParagraphCell supports StyledText, Markup and Hyperlink. I also want to add image in ParagraphCell.

**Comment by vandeseer** [comment]
The `ParagraphCell` is only a wrapper to [pdfbox-layout](https://github.com/ralfstuckert/pdfbox-layout)'s `Paragraph`. Since such a paragraph does not support images, the wrapper cell type doesn't either. As of now I do not plan to implement this feature, but the architecture of easytable allows you to create your own custom cell types :wink:
