### ISSUE TITLE
Can we specify the rowspan dynamically?

### ISSUE THREAD

**Issue by vikramtambe** [vandeseer/easytable#78]
I have a requirement where i have to display image on right hand side of table and actual data on left hand side. The data is dynamic hence i cant hardcode the rowspan for given image. e.g

In most of the examples we are specifying hard coded row span value and add the exact rows mentioned in rowspan. 

![image](https://user-images.githubusercontent.com/24460200/76337951-1430a380-62c6-11ea-9848-301a9525d2df.png)

**Comment by vandeseer** [comment]
I don't really understand the problem. Isn't it possible to do one intermediary step and just see how many rows will be generated and in a second step generate the table with `rowSpan` being set correctly? This whole problem seems more a general programming question to me than a specific question or issue with easytable. 

From a user's point of view that could be a convenient add-on. Sure. But I refrain from implementing it for now because I think it will add too much complexity for what it brings value.

**Comment by vikramtambe** [comment]
Thanks @vandeseer .  I was trying to check it whether we can simply it in user table. I have made changes and able to resolve the issue but after implementation i am getting error at Table.java for below code. What i found that even though I have 3 column table the columIndex became 3 resulting in ArrayIndexOutOfBoundException. 

Column column = table.getColumns().get(columnIndex);
